version: '3.8'

services:

  # ============================
  # USER SERVICE (H2 embedded DB)
  # ============================
  user-service:
    build:
      context: ./user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default

  # ============================
  # MYSQL DATABASE FOR ORDER SERVICE
  # ============================
  order-mysql:
    image: mysql:8
    container_name: order-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orderdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

  # ============================
  # ORDER SERVICE
  # ============================
  order-service:
    build:
      context: ./order-service
    ports:
      - "8082:8082"
    depends_on:
      - user-service
      - order-mysql
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/order_service_db?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  # ============================
  # MONGODB DATABASE FOR PRODUCT SERVICE
  # ============================
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # ============================
  # PRODUCT SERVICE
  # ============================
  product-service:
    build:
      context: ./product-service
    ports:
      - "8083:8083"
    depends_on:
      - mongo
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/productdb

volumes:
  mysql_data:
  mongo_data:
